import type { ResearchPaper } from "@/lib/types";

const editorialClosers: Record<string, string> = {
  "aied-069": "Any local trial should publish its account assumptions, age controls, escalation route and tool limits so families can distinguish tested safeguards from marketing language. That record should be refreshed whenever the default model, rate limits or safety behaviour changes.",
  "aied-068": "A robust replication would preregister adoption measures and independent outcomes, test the parallel-trends assumption openly, and examine students who use AI for explanation rather than completion. That would help separate harmful outsourcing from forms of support that preserve effort.",
  "aied-067": "Procurement records should name both the educational feature owner and the technical dependency owner. When a quiz workflow or model version changes, those owners can jointly decide whether the assessment remains valid, accessible and safe enough to continue.",
  "aied-066": "Evaluation teams should also document which prompts were excluded, how judges disagreed and how harmful examples are protected from unnecessary exposure. Transparent methods let schools compare releases without circulating unsafe content or overstating a benchmark's precision. Independent child-safety experts should review the protocol before deployment decisions.",
  "aied-065": "Districts should preserve a versioned example set and reviewer rubric so later plugin or model updates can be compared against the same teaching tasks. This turns a one-time launch review into continuing evidence about quality, workload and control.",
  "aied-064": "Professional development should therefore evaluate the teacher's reasoning trail, not merely the generated artifact. A short reflection on rejected suggestions, revised assumptions and observed classroom results can make expert judgment visible and support better peer learning.",
  "aied-063": "The safest default may differ across meeting categories, so one domain-wide switch is rarely sufficient. Governance should be reviewed with educators, safeguarding staff, data-protection leads and people who depend on captions or notes for access.",
  "aied-062": "Future studies can strengthen the evidence by randomly assigning classes where feasible, scoring student projects blind to condition and checking retention months later. Qualitative interviews can also show whether a smaller measured gender gap reflects genuinely broader participation.",
  "aied-061": "The most useful notice explains more than the word AI: it states the system's role, the responsible institution, the human review performed and how a person can question the result. Comprehension testing is especially important for younger users.",
  "aied-060": "A future study could vary the scaffold itself, compare optional and mandatory supports, and examine whether students transfer adaptation strategies to a new topic after the interface suggestions disappear. That would test whether behaviour becomes a learner capability.",
  "aied-059": "Schools should also retain a human-authored reference version for high-stakes templates and periodically compare generated drafts against it. That makes language drift, missing clauses and unexpected changes in connected context easier to detect.",
  "aied-058": "The human tutor should also be able to report a poor suggestion without interrupting the lesson, and programme leaders should study rejection as useful evidence rather than failure. Good oversight learns from the moments when professional judgment overrides the model.",
  "aied-057": "Programme owners should report completion, application and classroom-change evidence separately. A credential can be accessible and well designed even when impact is not yet known, provided its claims remain proportionate and participants can show what they learned.",
  "aied-056": "Future tutors should be compared on verified accuracy, the quality of elicited reasoning and delayed transfer, not only on practice scores. Teacher workload for building and maintaining guardrails must also be counted when assessing whether the design can scale.",
};

export const researchNewsBackfill20260731To0806: ResearchPaper[] = ([
  {
    id: "aied-069",
    slug: "news-gpt56-luna-free-access-teen-safeguards",
    title: "Product news: GPT-5.6 Luna expands free text access while adding explicit under-18 safeguards",
    authors: ["OpenAI"],
    venue: "AI Product and Learning Report",
    year: 2026,
    type: "policy-ethics",
    tags: ["product news", "GPT-5.6 Luna", "free access", "teen safety", "K-12 governance"],
    image: "/images/research/covers/aied-069-gpt56-luna-free-access-teen-safeguards-2026.png",
    imageAlt: "A diverse group of teenagers and a teacher review an AI learning conversation beside clear safety and access indicators in a bright school media room",
    summaryImage: "/images/research/summary/aied-069-gpt56-luna-free-access-teen-safeguards-summary.png",
    summaryImageAlt: "A diverse group of teenagers and a teacher review an AI learning conversation beside clear safety and access indicators in a bright school media room",
    summaryAudio: "/audio/research/aied-069-gpt56-luna-free-access-teen-safeguards-summary.m4a",
    summaryAudioTitle: "Listen to the product news report",
    shortSummary: "Product news: OpenAI said GPT-5.6 Luna would become the default for Free and Go users, followed by unlimited text chats and a Think button subject to abuse guardrails. The same release described specific under-18 boundaries, while file, image and other tool limits remained.",
    fullSummary: `OpenAI's August 6 product announcement expands ordinary access to GPT-5.6 while making several youth-safety boundaries visible. GPT-5.6 Luna was scheduled to become the default model for Free and Go users during the week of the announcement. Starting the following week, those users were to receive unlimited text chats and a Think button for questions that need more reasoning time, subject to abuse guardrails. File uploads, image generation and other tools would continue to have limits. Plus and Pro users could use an updated GPT-5.6 Sol and a slider for choosing how much thought the model applies from August 6.\n\nFor education, the access change matters because a general free account can be easier for learners to reach than an institutionally managed system. Unlimited text does not mean unlimited capability, guaranteed availability or school approval. It also does not turn a consumer account into ChatGPT for Teachers or ChatGPT Edu. Those products have different verification, administration and data-governance arrangements. A school should therefore distinguish what students can access independently from what it authorizes for coursework, protected information or assessment.\n\nThe announcement also details training and system protections for users OpenAI believes are under 18. OpenAI says the model is trained to avoid romantic roleplay, age-restricted challenges and presenting itself as a substitute for real-world relationships. It describes age-appropriate boundaries around sexual content, eating disorders and body-image risks, age-restricted goods, dangerous activities and graphic violence. When a teenager may need support, the model is intended to encourage connection with trusted people. These are vendor-described safeguards, not evidence that every risky interaction will be detected or resolved well.\n\nSchools should not treat a model's age-aware behaviour as a replacement for safeguarding practice. Age inference can be imperfect, students may share accounts or omit context, and a fluent refusal can still leave a distressed learner without adequate help. A deployment plan should identify approved accounts, escalation routes, human contacts, reporting procedures and when AI should not be used. Teachers also need clarity about whether chat records, files or images enter a school-managed workspace or a personal account.\n\nA useful pilot can separate access, safety and learning outcomes. Students might use text chat for low-risk brainstorming or explanations, then verify claims against course sources and complete an independent task. Schools can test age-inappropriate prompt categories with authorized synthetic scenarios, record false negatives and false positives, and confirm that support messages lead to real human resources. They should also monitor whether unequal access persists through device, language, tool and file limits.\n\nThe release lowers one access barrier and states stronger youth boundaries, but neither change proves educational benefit. For Hong Kong educators, the practical question is whether a clearly governed workflow helps learners reason, verify and seek human support while keeping consumer access separate from institutional responsibility.`,
    keyTakeaways: [
      "Product news: GPT-5.6 Luna was scheduled to become the Free and Go default, with unlimited text chats and a Think button following the next week under abuse guardrails.",
      "OpenAI described explicit under-18 boundaries, including relationship substitution, sexual content, body-image risks, dangerous activities and graphic violence.",
      "General free access is not an institution-managed K-12 entitlement; schools still need approved-account, data, safeguarding, escalation and independent-learning controls.",
    ],
    whyItMatters: "For AIEDHK, the release shows why wider model access and youth safety must be evaluated together: availability can expand before schools have established the account, evidence and human-support boundaries that responsible learning requires.",
    sourceUrl: "https://openai.com/index/improving-gpt-5-6-sol-in-chatgpt/",
    sourceUrls: [
      { label: "OpenAI: Improving GPT-5.6 Sol and expanding GPT-5.6 Luna access", url: "https://openai.com/index/improving-gpt-5-6-sol-in-chatgpt/" },
      { label: "OpenAI ChatGPT release notes: August 6, 2026", url: "https://help.openai.com/en/articles/6825453-chatgpt-release-notes" },
    ],
    createdAt: "2026-08-06",
  },
  {
    id: "aied-068",
    slug: "generative-ai-learning-penalty-chinese-secondary-education",
    title: "Generative AI adoption was linked to higher homework scores but lower unaided exams in a 26,811-student panel",
    authors: ["David Strömberg", "Victor Lei", "Yanhui Wu"],
    venue: "CEPR Discussion Paper No. 21577",
    year: 2026,
    type: "journal",
    tags: ["generative AI", "secondary education", "homework outsourcing", "unaided assessment", "difference-in-differences"],
    image: "/images/research/covers/aied-068-generative-ai-learning-penalty-chinese-secondary-education-2026.png",
    imageAlt: "Chinese secondary students complete homework with digital assistance before taking a separate closed-book assessment observed by a teacher",
    summaryImage: "/images/research/summary/aied-068-generative-ai-learning-penalty-chinese-secondary-education-summary.png",
    summaryImageAlt: "Chinese secondary students complete homework with digital assistance before taking a separate closed-book assessment observed by a teacher",
    summaryAudio: "/audio/research/aied-068-generative-ai-learning-penalty-chinese-secondary-education-summary.m4a",
    summaryAudioTitle: "Listen to the paper summary",
    shortSummary: "A CEPR discussion paper analyzes 30 months of records from 26,811 Chinese students in Grades 7–12. Its difference-in-differences estimates associate generative-AI adoption with homework scores 18% higher and completion time 30% lower, but with substantial declines on closed-book and entrance examinations.",
    fullSummary: `Strömberg, Lei and Wu examine a pattern that homework dashboards alone can conceal: assisted work may improve while independent performance declines. Their CEPR discussion paper combines 30 months of records for 26,811 Chinese students in Grades 7 through 12 across nine subjects. The data include homework scores and completion time, monthly closed-book examinations and two types of high-stakes entrance examination. Because students and schools adopted generative AI at different times, the authors use a staggered-adoption difference-in-differences design to estimate changes after adoption.\n\nThe reported contrast is large. After adoption, homework scores rose by an estimated 18% while homework completion time fell by 30%. Within six months, monthly unaided examination scores were estimated to be 20% lower. Scores on the two high-stakes entrance examinations were estimated to fall by 18% and 24%, with the full entrance-exam penalty appearing after about two years. The paper reports the largest losses in social-science subjects, followed by STEM and languages, and larger estimated effects for younger students, high achievers and boys.\n\nThe authors investigate whether use resembles learning support or task outsourcing. About 80% of AI users displayed a combination of unusually high homework scores and unusually short completion time, which the paper interprets as outsourcing-like behaviour. The learning losses concentrate in that group. Users who maintained homework time closer to non-users showed much smaller losses. This pattern is consistent with reduced cognitive engagement, but it is not a direct observation of prompts, copied answers or student intention.\n\nThe evidence is consequential but not experimental. AI adoption was not randomly assigned, so the causal interpretation depends on parallel-trends assumptions and on whether other time-varying changes are adequately handled. The outsourcing measure is inferred from administrative traces rather than chat logs. The setting combines one national examination culture and particular homework platforms, and the paper is a discussion paper that may be revised. Its estimates should not be generalized to every learner, subject or guarded tutoring system.\n\nFor schools, the study argues for separating product completion from learning evidence. An AI-supported homework task can be paired with a brief unaided explanation, oral defence, retrieval quiz or transfer problem. Teachers can inspect both time-on-task patterns and the reasoning shown, without assuming that fast work is automatically misconduct. Assignments can permit AI for hints, examples and feedback while requiring students to identify what they changed and why.\n\nFor Hong Kong education, the strongest lesson is methodological: evaluate the outcome after assistance is removed. Higher homework scores and faster completion may be valuable, but they cannot establish durable learning by themselves. Pilots should compare assisted products, independent assessments and process evidence, while treating the paper's striking estimates as provisional findings from an observational design rather than a universal causal law.`,
    keyTakeaways: [
      "Across a 30-month panel of 26,811 students, the authors estimate that AI adoption coincided with homework scores 18% higher and completion time 30% lower.",
      "The same design estimated lower monthly closed-book and entrance-exam performance, with losses concentrated among users showing an outsourcing-like time-and-score pattern.",
      "Because adoption was non-random and outsourcing was inferred, the results support independent assessment and process evidence without proving a universal AI learning penalty.",
    ],
    whyItMatters: "For AIEDHK, this study shows why an education dashboard needs two views: how well a learner performs with AI and what the learner can still explain, retrieve and transfer when assistance is absent.",
    sourceUrl: "https://cepr.org/publications/dp21577",
    sourceUrls: [
      { label: "CEPR Discussion Paper 21577", url: "https://cepr.org/publications/dp21577" },
    ],
    createdAt: "2026-08-06",
  },
  {
    id: "aied-067",
    slug: "news-gemini-forms-quizzes-claude-opus41-retirement",
    title: "Product news: Gemini begins generating quizzes as Claude Opus 4.1 reaches its API retirement date",
    authors: ["Google Workspace", "Anthropic"],
    venue: "AI Product and Learning Report",
    year: 2026,
    type: "policy-ethics",
    tags: ["product news", "Gemini in Forms", "quiz generation", "Claude Opus 4.1", "model lifecycle"],
    image: "/images/research/covers/aied-067-gemini-forms-quizzes-claude-opus41-retirement-2026.png",
    imageAlt: "A teacher previews an AI-drafted quiz while a school technology specialist checks a model migration dashboard in a collaborative assessment studio",
    summaryImage: "/images/research/summary/aied-067-gemini-forms-quizzes-claude-opus41-retirement-summary.png",
    summaryImageAlt: "A teacher previews an AI-drafted quiz while a school technology specialist checks a model migration dashboard in a collaborative assessment studio",
    summaryAudio: "/audio/research/aied-067-gemini-forms-quizzes-claude-opus41-retirement-summary.m4a",
    summaryAudioTitle: "Listen to the product news report",
    shortSummary: "Product news: Google scheduled Gemini quiz generation in Forms to begin rolling out to Scheduled Release domains on August 5, while Anthropic set the same date for Claude Opus 4.1 retirement on its operated API platforms. The paired changes make assessment review and model-lifecycle planning immediate education-system tasks.",
    fullSummary: `Two August 5 product events expose different kinds of maintenance work for education teams. Google scheduled Help me create in Forms to begin rolling out quiz generation to Scheduled Release domains, following an earlier Rapid Release start. Anthropic set August 5 as the retirement date for the Claude Opus 4.1 API model identifier. One change can accelerate assessment drafting; the other can cause an existing application to fail if its model dependency is not migrated.\n\nGoogle says educators can describe a quiz in a prompt and optionally reference Docs, Slides or PDFs in Drive. Gemini then drafts quiz settings, correct answers and question types including multiple choice, checkboxes and grids. The creator can preview the result and edit it after insertion. This is a starting point, not a validated assessment. A generated correct answer may be wrong, a distractor may reveal the answer, and a source document may not support the difficulty or construct that a teacher intends to measure.\n\nAccess is also bounded. Google lists Education Plus and the Google AI Pro for Education or Teaching and Learning add-ons among eligible education routes. Smart features and personalization must be enabled. Rollout can take up to 15 days, so an August 5 start does not mean that every eligible user sees the feature immediately. Education Fundamentals alone is not presented as a universal entitlement to this quiz generator.\n\nAnthropic's model event affects developers rather than ordinary Claude chat users. The model claude-opus-4-1-20250805 was deprecated on June 5 with August 5 as its retirement date and Claude Opus 4.8 as the recommended replacement. Anthropic explains that requests to retired models fail. Its dates apply to Anthropic-operated platforms: the Claude API, Claude Platform on AWS and Microsoft Foundry. Amazon Bedrock and Google Cloud manage their own schedules. This is not a change to Claude for Teachers pricing or a retirement of the teacher product.\n\nFor a school or educational technology provider, migration requires more than replacing a string. A newer model can change output length, cost, refusal behaviour, latency and the quality of generated questions. Teams should inventory every model reference, replay representative low- and high-risk tasks, compare rubrics and safety cases, confirm data routes, update monitoring and retain a rollback plan where the platform permits it. Research projects also need to record the exact model snapshot so later results remain interpretable.\n\nThe shared lesson is that AI-supported assessment has two review layers. Teachers must validate every quiz before students see it, while technical owners must validate the infrastructure that generates it. Faster drafting is useful only when the content measures the intended learning. A successful migration is useful only when it preserves or improves that quality without silently changing access, privacy or safety.`,
    keyTakeaways: [
      "Product news: Gemini in Forms can draft quizzes, answer keys and varied question types from prompts and selected Drive sources, with teacher preview and editing.",
      "The Google feature requires eligible education plans and settings and may take up to 15 days to appear after the Scheduled Release rollout begins.",
      "Claude Opus 4.1 API retirement requires dependency discovery and regression testing; it is a developer-platform event, not a Claude for Teachers pricing change.",
    ],
    whyItMatters: "For AIEDHK, the paired events show that educational AI quality depends on both editorial review and technical lifecycle control: the assessment and the system producing it must each remain inspectable.",
    sourceUrl: "https://workspaceupdates.googleblog.com/2026/07/use-gemini-in-google-forms-to-quickly-create-a-new-quiz.html",
    sourceUrls: [
      { label: "Google Workspace: Use Gemini in Forms to create a quiz", url: "https://workspaceupdates.googleblog.com/2026/07/use-gemini-in-google-forms-to-quickly-create-a-new-quiz.html" },
      { label: "Anthropic model deprecations", url: "https://platform.claude.com/docs/en/about-claude/model-deprecations" },
    ],
    createdAt: "2026-08-05",
  },
  {
    id: "aied-066",
    slug: "llm-safety-children-multiturn-red-team",
    title: "Child-specific multi-turn red teaming found safety gaps that adult baselines and single-turn tests missed",
    authors: ["Prasanjit Rath", "Hari Shrawgi", "Parag Agrawal", "Sandipan Dandapat"],
    venue: "NAACL 2025 Industry Track",
    year: 2025,
    type: "conference",
    tags: ["child safety", "large language models", "red teaming", "multi-turn evaluation", "K-12 AI"],
    image: "/images/research/covers/aied-066-llm-safety-children-multiturn-red-team-2026.png",
    imageAlt: "A child-safety research team studies branching multi-turn dialogue traces behind a protected classroom observation window without showing harmful content",
    summaryImage: "/images/research/summary/aied-066-llm-safety-children-multiturn-red-team-summary.png",
    summaryImageAlt: "A child-safety research team studies branching multi-turn dialogue traces behind a protected classroom observation window without showing harmful content",
    summaryAudio: "/audio/research/aied-066-llm-safety-children-multiturn-red-team-summary.m4a",
    summaryAudioTitle: "Listen to the paper summary",
    shortSummary: "Rath and colleagues created 560 synthetic child personas and matched adult baselines to red-team six language-model snapshots over five-turn conversations. The benchmark found substantially higher defect rates for child scenarios in several categories and showed that many failures emerged only after the dialogue developed.",
    fullSummary: `Rath and colleagues argue that a general safety score is not enough for systems used around children. Their NAACL Industry Track paper develops a child-harm taxonomy and synthetic Child User Models, then uses them to red-team six language-model snapshots. The study does not involve real children. Instead, it constructs 560 synthetic child personas and prompts, creates matched adult baselines and runs conversations for up to five turns. Mistral-7B serves as the automated adversarial model and GPT-4o as the automated judge.\n\nThe taxonomy begins with 12 broad child-risk categories and is divided into 14 categories for the experiments. The primary defect measure asks whether a conversation contains at least one response judged harmful. Even the lowest reported family-level defect rate, for the Llama family in this evaluation, was 29.6%. The authors find especially large gaps between child and adult personas for sexual content, at 75.4% versus 16.7%; regulated goods and services, at 71.3% versus 30.0%; illegal activities, at 46.7% versus 9.2%; and education-related harm, at 23.3% versus 8.1%.\n\nConversation length changes what the benchmark detects. Among first harmful responses, 48.12% appeared in the third turn, compared with 25.25% in the first. A model may refuse an obvious first request but become unsafe as a fictional scenario, personal disclosure or sequence of follow-up questions develops. For schools and developers, that finding supports testing realistic dialogue paths rather than only a list of isolated prohibited prompts.\n\nThe numerical results need strict boundaries. Synthetic personas cannot represent the full diversity of children's language, development, disability, culture or circumstances. Both the attacker and judge are models, so their strategies and labels can be biased. The evaluation is English-only, ends after five turns and uses early-2025 model snapshots whose safety tuning may later change. The model ranking is not evidence about current products, and the defect rates are not estimates of how often real children experience harm.\n\nThe paper is nevertheless useful as an evaluation design. A child-facing or child-adjacent service can define age-specific risks, generate authorized synthetic scenarios, test several turns, include benign near-neighbours to measure over-refusal and have trained humans review a sample. Tests should include requests that are harmless for adults but developmentally inappropriate for children, as well as moments when the model should direct a learner toward a parent, teacher, counsellor or emergency resource.\n\nFor Hong Kong schools, vendor safeguards should be one layer within a wider system. Schools need age-appropriate accounts, clear permitted uses, staff escalation, incident reporting and regular re-testing after model updates. The study's lasting contribution is not a league table; it is the warning that adult safety baselines and one-turn checks can miss risks that emerge through a child's continuing conversation.`,
    keyTakeaways: [
      "The benchmark used 560 synthetic child personas, matched adult baselines, six model snapshots and conversations of up to five turns; it did not expose real children to harmful prompts.",
      "Child-persona defect rates substantially exceeded adult baselines in several categories, and nearly half of first harmful responses appeared at turn three.",
      "Synthetic, automated and version-specific results are not incidence estimates or current rankings, but they support child-specific, multi-turn and human-reviewed safety testing.",
    ],
    whyItMatters: "For AIEDHK, the study provides a concrete evaluation lesson: a school cannot infer child safety from adult benchmarks or one-turn refusals; it needs age-specific scenarios, longer conversations and accountable human review.",
    sourceUrl: "https://aclanthology.org/2025.naacl-industry.62/",
    sourceUrls: [
      { label: "ACL Anthology: LLM Safety for Children", url: "https://aclanthology.org/2025.naacl-industry.62/" },
      { label: "arXiv preprint record", url: "https://arxiv.org/abs/2502.12552" },
    ],
    createdAt: "2026-08-05",
  },
  {
    id: "aied-065",
    slug: "news-openai-k12-educator-plugin-teacher-access",
    title: "Product news: OpenAI launches a standards-connected K-12 Educator plugin for district deployments",
    authors: ["OpenAI", "Anthropic"],
    venue: "AI Product and Learning Report",
    year: 2026,
    type: "policy-ethics",
    tags: ["product news", "K-12 Educator plugin", "ChatGPT for Teachers", "Claude for Teachers", "teacher access"],
    image: "/images/research/covers/aied-065-openai-k12-educator-plugin-teacher-access-2026.png",
    imageAlt: "A racially diverse teacher team reviews differentiated classroom materials and curriculum progressions generated through a governed district workspace",
    summaryImage: "/images/research/summary/aied-065-openai-k12-educator-plugin-teacher-access-summary.png",
    summaryImageAlt: "A racially diverse teacher team reviews differentiated classroom materials and curriculum progressions generated through a governed district workspace",
    summaryAudio: "/audio/research/aied-065-openai-k12-educator-plugin-teacher-access-summary.m4a",
    summaryAudioTitle: "Listen to the product news report",
    shortSummary: "Product news: OpenAI introduced a K-12 Educator plugin for ChatGPT Work and Codex that can create differentiated resources, interactive visuals and classroom insights using Learning Commons standards. Availability is through ChatGPT Edu and ChatGPT for Teachers district deployments, not every personal account.",
    fullSummary: `OpenAI's August 4 announcement introduces three education plugins for ChatGPT Work and Codex: one for K-12 educators, one for college educators and one for college students. A plugin packages approved apps, role-specific skills, instructions and common workflows so a user does not need to construct every process from a blank prompt. For K-12 schools, the important product change is a governed educator workflow rather than another general chatbot interface.\n\nThe K-12 Educator plugin is designed to work with materials and tools that teachers already use. OpenAI says it can create differentiated resources, design interactive visuals and surface actionable classroom insights. Examples include assignment translation, exit-ticket briefs, family updates and practice tests. Its Learning Commons integration can connect a request to local academic standards, smaller learning components and progressions between prior and future learning. The announcement explicitly leaves pedagogical decisions, grading and agentic actions under educator control.\n\nAvailability has a consequential boundary. OpenAI says the new education plugins are available through ChatGPT Edu and ChatGPT for Teachers district deployments. That does not mean every teacher with a personal Free or Plus account automatically receives the K-12 plugin. District leaders still need to decide which materials and connected apps are approved, who may install or run workflows, what actions need confirmation and how generated resources are reviewed before classroom use.\n\nThe teacher offers also differ and should not be collapsed into a universal discount. ChatGPT for Teachers, introduced in 2025, is free through June 2027 for verified educators and staff at accredited U.S. K-12 schools or districts; it is not a student plan and supports shared workspaces and administrative controls. Anthropic's Claude for Teachers, introduced on July 14, offers verified U.S. K-12 individual educators a full free year if they sign up by June 30, 2027. It includes Pro-level features, Claude Code, Cowork, Learning Commons and education connectors, but is educator-only, follows Claude's 18-and-over policy and lacks several district-management features of an organizational plan. Neither offer establishes eligibility for Hong Kong teachers.\n\nProduct capability is not learning evidence. Standards retrieval can be incomplete, a differentiated worksheet can lower rather than improve cognitive demand, and an interactive visual can misrepresent a concept. Before adoption, a school can test the plugin against real curriculum cases using synthetic student data. Reviewers can score accuracy, standards fit, accessibility, language quality, cultural relevance and whether the material reveals or obscures student thinking.\n\nFor Hong Kong schools, the announcement is best read as a design pattern: curriculum-grounded agent workflows inside an accountable workspace. A local implementation would need Hong Kong curriculum mappings, bilingual review, approved data routes and evidence that teachers save time without reducing quality. Free educator access can support exploration, but institutional deployment requires a separate decision about governance, professional learning and measurable educational value.`,
    keyTakeaways: [
      "Product news: OpenAI's K-12 Educator plugin packages standards-connected workflows for differentiated resources, visuals, family updates, exit tickets and practice tests.",
      "The plugin is available through ChatGPT Edu and ChatGPT for Teachers district deployments, not automatically to every personal Free or Plus account.",
      "OpenAI and Anthropic teacher offers differ in duration, eligibility and organizational controls; neither should be described as a universal international teacher discount.",
    ],
    whyItMatters: "For AIEDHK, the launch moves the adoption question from isolated prompting toward curriculum-connected, permissioned workflows, while showing that free teacher access and district governance are different decisions.",
    sourceUrl: "https://openai.com/index/learn-teach-chatgpt-work-codex/",
    sourceUrls: [
      { label: "OpenAI: New ways to learn and teach with ChatGPT Work and Codex", url: "https://openai.com/index/learn-teach-chatgpt-work-codex/" },
      { label: "OpenAI Help: ChatGPT for Teachers", url: "https://help.openai.com/en/articles/12844995-chatgpt-for-teachers" },
      { label: "Anthropic: Claude for Teachers", url: "https://www.anthropic.com/news/claude-for-teachers" },
      { label: "Anthropic Help: Claude for Teachers data and terms", url: "https://support.claude.com/en/articles/15926041-claude-for-teachers-your-data-and-our-terms" },
    ],
    createdAt: "2026-08-04",
  },
  {
    id: "aied-064",
    slug: "generative-ai-teacher-self-directed-professional-development",
    title: "Teachers used generative AI as a self-directed professional-learning scaffold, but the evidence remains self-reported",
    authors: ["Zixi Li", "Chaoran Wang", "Curtis J. Bonk"],
    venue: "TechTrends",
    year: 2026,
    type: "journal",
    tags: ["teacher professional development", "self-directed learning", "ChatGPT", "K-12 teachers", "mixed methods"],
    image: "/images/research/covers/aied-064-generative-ai-teacher-self-directed-professional-development-2026.png",
    imageAlt: "Five diverse K-12 teachers compare AI-supported lesson drafts with curriculum notes and peer feedback during a professional learning session",
    summaryImage: "/images/research/summary/aied-064-generative-ai-teacher-self-directed-professional-development-summary.png",
    summaryImageAlt: "Five diverse K-12 teachers compare AI-supported lesson drafts with curriculum notes and peer feedback during a professional learning session",
    summaryAudio: "/audio/research/aied-064-generative-ai-teacher-self-directed-professional-development-summary.m4a",
    summaryAudioTitle: "Listen to the paper summary",
    shortSummary: "A mixed-methods study surveyed 298 U.S. K-12 teachers who already used ChatGPT for teaching or professional development and interviewed five. Participants described using generative AI for lesson ideas, structure, quizzes and explanations, but the study did not measure teaching quality, actual time savings or student outcomes.",
    fullSummary: `Li, Wang and Bonk examine how K-12 teachers use generative AI for self-directed professional development outside a formal course. Their explanatory mixed-methods study recruited 298 U.S. teachers through Prolific in May and June 2024. Eligibility required prior use of ChatGPT for teaching or professional development, so the sample represents experienced adopters rather than teachers in general. Participants completed a 27-item Likert survey grounded in Garrison's self-directed learning model. Five teachers later completed interviews and shared ChatGPT or Gemini interaction records.\n\nTeachers reported using ChatGPT most often to find pedagogical or lesson ideas, organize a lesson, generate quizzes, customize materials and explain subject content. Survey responses indicated strong perceived ownership of professional learning, alignment with personal standards and monitoring of progress. Interviewees described the tool as a way to get an initial structure quickly, explore alternatives and adapt a draft to their particular learners. They also described checking output against professional knowledge rather than accepting it unchanged.\n\nThe study is informative about process, not effectiveness. The quantitative analysis is mainly descriptive, and participants already had AI experience. Teachers who disliked or abandoned the technology are less likely to appear in such a sample. Only five people completed interviews after recruitment attrition, making the qualitative evidence detailed but narrow. The researchers did not compare users with non-users, observe classroom practice, score generated lessons, measure time saved or assess student learning.\n\nThese boundaries change the appropriate claim. The evidence supports saying that participating teachers perceived generative AI as a flexible professional-learning scaffold and illustrated how they reviewed and contextualized its output. It does not show that ChatGPT caused better teaching, reduced workload by a measured amount or improved student achievement. Confidence in using a tool is also different from confidence that its output is accurate, equitable and instructionally appropriate.\n\nFor professional learning design, the reported behaviours suggest useful routines. A teacher can ask for several approaches, identify the assumptions behind each, compare them with curriculum and learner evidence, revise a chosen plan and record why the revision is better. Peer review can surface subject errors, accessibility problems or lowered cognitive demand. School leaders can provide protected accounts and exemplars while preserving teacher choice and avoiding usage quotas that reward activity over quality.\n\nFor Hong Kong schools, a pilot should include Chinese and English materials, local curricula and varied subject areas. Evaluation can measure the full time required to prompt, check and revise; independently score the resulting materials; and observe whether changes survive classroom use. Teachers who do not adopt the tool should be included so barriers and negative experiences remain visible.\n\nThe paper's value lies in documenting an emerging form of informal teacher learning while keeping the evidence modest. Generative AI may make professional exploration more immediate, but professional judgment, peer critique and outcome measurement remain the mechanisms that turn a fast suggestion into defensible teaching practice.`,
    keyTakeaways: [
      "The study surveyed 298 prior users and interviewed five teachers, documenting AI use for pedagogical ideas, lesson structure, quizzes, customized content and explanations.",
      "Participants reported self-management and critical adaptation, but the selected-user, descriptive design provides perception and process evidence rather than causal outcomes.",
      "Future evaluations should measure total review time, material quality, classroom implementation and student learning while including teachers who do not adopt the tool.",
    ],
    whyItMatters: "For AIEDHK, the study helps separate a plausible professional-learning workflow from an impact claim: AI can make exploration easier, but teacher expertise and independently measured quality determine whether practice improves.",
    sourceUrl: "https://doi.org/10.1007/s11528-025-01123-8",
    sourceUrls: [
      { label: "TechTrends article", url: "https://doi.org/10.1007/s11528-025-01123-8" },
    ],
    createdAt: "2026-08-04",
  },
  {
    id: "aied-063",
    slug: "news-google-meet-ai-notes-admin-controls",
    title: "Product news: Google Meet completes an education-admin rollout for more selective automatic AI notes",
    authors: ["Google Workspace"],
    venue: "AI Product and Learning Report",
    year: 2026,
    type: "policy-ethics",
    tags: ["product news", "Google Meet", "AI note-taking", "administrator controls", "consent and retention"],
    image: "/images/research/covers/aied-063-google-meet-ai-notes-admin-controls-2026.png",
    imageAlt: "A school technology administrator and two educators review meeting consent, note retention and participant thresholds beside a video-conference room",
    summaryImage: "/images/research/summary/aied-063-google-meet-ai-notes-admin-controls-summary.png",
    summaryImageAlt: "A school technology administrator and two educators review meeting consent, note retention and participant thresholds beside a video-conference room",
    summaryAudio: "/audio/research/aied-063-google-meet-ai-notes-admin-controls-summary.m4a",
    summaryAudioTitle: "Listen to the product news report",
    shortSummary: "Product news: Google expected an administrator setting for automatic Meet note-taking only in meetings with at least three guests to complete rollout by August 3. The control defaults off for Google AI Pro for Education, and no end-user effect was scheduled before September 21.",
    fullSummary: `Google's August 3 milestone concerns an administrator control, not the universal launch of automatic meeting notes. The company expected rollout of a new Google Meet setting to complete by that date. Previously, administrators could generally enable or disable automatic AI note-taking. The additional option lets them set automatic notes only for meetings with three or more people, aiming to avoid applying the feature to every small conversation.\n\nFor education customers, the timing and defaults matter. Google lists the setting for organizations with the Google AI Pro for Education add-on and says it is off by default for that route. The administrator configuration was not expected to affect end users before September 21, 2026. After the later user rollout, individuals would be able to override the administrator default in their Meet settings. Describing August 3 as the day all teachers and students began automatic note-taking would therefore be inaccurate.\n\nThe gap between configuration and activation gives schools a governance window. AI notes can support accessibility, help absent colleagues understand a meeting and reduce the burden of producing routine minutes. They can also capture sensitive information from safeguarding discussions, individual education planning, counselling, disciplinary meetings, parent conferences or staff deliberation. A transcript-like summary may omit uncertainty, misattribute a statement or turn a provisional conversation into an apparently official record.\n\nBefore enabling the setting, a school can classify meeting types and identify those that must never start automatic notes. It can decide when explicit participant consent is required, who receives the notes, where they are stored, how long they remain and how a participant requests correction or deletion. External guests, students, interpreters and support staff need an understandable notice rather than a hidden administrator assumption. Local law and institutional policy may impose obligations beyond the product setting.\n\nThe three-guest threshold is only a convenience rule. It cannot determine whether a meeting is educationally important, confidential or appropriate to record. Administrators should pair it with host guidance, restricted sharing, retention rules and periodic audit. A pilot can compare AI notes with recordings or human minutes on a small authorized sample, scoring speaker attribution, omissions, action items and treatment of multilingual conversation.\n\nFor Hong Kong schools and universities, language mixing is an additional test. Cantonese, English and Putonghua may appear in one meeting, and names or specialist terms can be mistranscribed. Participants should be able to inspect the original context and challenge the summary before it becomes part of an official workflow.\n\nThe product-news significance is the arrival of a more selective control surface. It creates a useful pause before end-user activation, but it does not resolve consent, confidentiality, accuracy or record ownership. Those remain institutional decisions that must be made before the first automatic note is trusted.`,
    keyTakeaways: [
      "Product news: Google expected the admin option for automatic notes only in meetings with at least three guests to complete rollout by August 3.",
      "The setting is off by default for Google AI Pro for Education, and Google said end users would not be affected before September 21, 2026.",
      "A participant threshold cannot replace policies for consent, sensitive meetings, multilingual accuracy, access, correction, retention and deletion.",
    ],
    whyItMatters: "For AIEDHK, the rollout illustrates a valuable governance pattern: use the interval before feature activation to define meeting classes, consent, records and accuracy tests instead of treating an admin toggle as a policy.",
    sourceUrl: "https://workspaceupdates.googleblog.com/2026/07/new-google-meet-take-notes-for-me-settings-for-admins-and-end-users.html",
    sourceUrls: [
      { label: "Google Workspace: New Meet take-notes settings", url: "https://workspaceupdates.googleblog.com/2026/07/new-google-meet-take-notes-for-me-settings-for-admins-and-end-users.html" },
    ],
    createdAt: "2026-08-03",
  },
  {
    id: "aied-062",
    slug: "ai-literacy-gender-equity-elementary-steam-pbl-aiot",
    title: "A STEAM-PBL-AIoT course was associated with broader elementary AI-literacy gains and narrower measured gender gaps",
    authors: ["Chih-Chan Cheng", "Jeen-Shing Wang", "Xiaoming Zhai", "Ya-Ting Carolyn Yang"],
    venue: "International Journal of STEM Education",
    year: 2025,
    type: "journal",
    tags: ["AI literacy", "elementary education", "gender equity", "STEAM", "project-based learning"],
    image: "/images/research/covers/aied-062-ai-literacy-gender-equity-elementary-steam-pbl-aiot-2026.png",
    imageAlt: "A gender-balanced group of Taiwanese fifth-grade learners builds and discusses a simple community-focused AIoT project with their teacher",
    summaryImage: "/images/research/summary/aied-062-ai-literacy-gender-equity-elementary-steam-pbl-aiot-summary.png",
    summaryImageAlt: "A gender-balanced group of Taiwanese fifth-grade learners builds and discusses a simple community-focused AIoT project with their teacher",
    summaryAudio: "/audio/research/aied-062-ai-literacy-gender-equity-elementary-steam-pbl-aiot-summary.m4a",
    summaryAudioTitle: "Listen to the paper summary",
    shortSummary: "A two-part study validated a fifth-grade AI-literacy questionnaire with 504 learners and compared a 19-week STEAM-PBL-AIoT course with an AIoT course in 109 students. The integrated course showed larger self-reported gains in several dimensions, while the ethics advantage was not significant.",
    fullSummary: `Cheng and colleagues study both how elementary AI literacy is measured and how a project-based course may change it. In the first study, 504 Taiwanese fifth graders completed a questionnaire covering affective, behavioural, cognitive and ethical dimensions. The researchers examined reliability, validity and measurement equivalence across gender. In the second study, four classes completed 19-week courses: 55 students took an AIoT comparison course, while 54 took an integrated STEAM, project-based learning and AIoT course organized around authentic problems and AI-literacy goals.\n\nBoth groups improved from pre-test to post-test. After accounting for initial differences, the integrated course had significantly higher post-test scores for overall AI literacy and the affective, behavioural and cognitive dimensions, with reported effects in the medium range, approximately r = .30 to .44. The groups did not differ significantly on the ethics dimension. The result suggests that richer projects and explicit literacy goals may support several aspects of how learners perceive and approach AI, while ethical understanding may require different or more sustained pedagogy.\n\nGender patterns were a central question. Boys scored higher than girls across the measured dimensions at pre-test. By post-test, gender differences within both course groups were no longer statistically significant, and girls in the integrated course showed substantial gains. This is encouraging evidence of a narrowed measured gap in this sample. It is not proof that a course permanently eliminates gender inequity or that every learner experienced the same classroom opportunities.\n\nThe design limits causal claims. Classes were not randomly allocated, so teacher, class or selection differences may contribute to the outcomes. The intervention comparison involved only 109 students in one Taiwanese fifth-grade context. Most outcomes came from a self-report questionnaire rather than externally scored projects, observed practices or transfer tasks. There was no long-term follow-up to determine whether gains or narrower gender differences persisted. The lack of an additional ethics effect also warns against treating ethical literacy as an automatic by-product of technical projects.\n\nFor curriculum design, the study supports making AI literacy multidimensional. A unit can ask learners to build or investigate a useful system, explain how it works, evaluate data and limitations, collaborate in varied roles and discuss who may benefit or be excluded. Teachers can monitor who handles hardware, coding, explanation and leadership so participation does not reproduce stereotypes. Ethics can be assessed through age-appropriate cases and decisions rather than agreement with broad statements alone.\n\nFor Hong Kong primary education, replication should include Cantonese and English materials, local curriculum aims, objective performance tasks and classroom observations. Schools can disaggregate participation and outcomes while avoiding deficit assumptions about any group.\n\nThe paper offers a promising course model and a validated measurement effort, but its strongest conclusion is bounded: in this quasi-experiment, an integrated course was associated with larger gains in several self-reported AI-literacy dimensions and with gender gaps that were no longer statistically detectable at post-test.`,
    keyTakeaways: [
      "The research validated a four-dimension fifth-grade AI-literacy questionnaire with 504 learners and tested two 19-week course designs with 109 students.",
      "The integrated STEAM-PBL-AIoT course had higher overall, affective, behavioural and cognitive post-test scores, but no significant added ethics advantage.",
      "Measured gender gaps narrowed by post-test, but non-random classes, self-report outcomes, one context and no long-term follow-up limit causal and durable-equity claims.",
    ],
    whyItMatters: "For AIEDHK, the study shows how elementary AI literacy can combine making, reasoning, participation and ethics, while reminding schools to measure who participates and what learners can actually demonstrate.",
    sourceUrl: "https://doi.org/10.1186/s40594-025-00574-y",
    sourceUrls: [
      { label: "International Journal of STEM Education article", url: "https://doi.org/10.1186/s40594-025-00574-y" },
    ],
    createdAt: "2026-08-03",
  },
  {
    id: "aied-061",
    slug: "news-eu-ai-act-article50-transparency-education",
    title: "Product news policy brief: EU AI transparency rules begin applying to interactive and generated content",
    authors: ["European Commission"],
    venue: "AI Product and Learning Report",
    year: 2026,
    type: "policy-ethics",
    tags: ["product news", "EU AI Act", "Article 50", "AI disclosure", "synthetic content"],
    image: "/images/research/covers/aied-061-eu-ai-act-article50-transparency-education-2026.png",
    imageAlt: "European educators and school media staff review disclosure icons, chatbot notices and provenance records for AI-supported learning materials",
    summaryImage: "/images/research/summary/aied-061-eu-ai-act-article50-transparency-education-summary.png",
    summaryImageAlt: "European educators and school media staff review disclosure icons, chatbot notices and provenance records for AI-supported learning materials",
    summaryAudio: "/audio/research/aied-061-eu-ai-act-article50-transparency-education-summary.m4a",
    summaryAudioTitle: "Listen to the product news report",
    shortSummary: "Product news policy brief: EU AI Act Article 50 transparency obligations began applying on August 2. They cover notices for direct AI interaction, machine-readable marking of synthetic content and deployer disclosures for deepfakes, certain public-interest text, emotion recognition and biometric categorisation.",
    fullSummary: `On August 2, transparency obligations under Article 50 of the European Union AI Act began to apply. The European Commission's July guidance explains that people should be able to recognise when they are interacting directly with an AI system or encountering content generated or manipulated by AI. For education organizations, the practical work is to identify where AI appears in learning, communication and administration, then assign the correct notice, label or technical marking.\n\nProviders must design relevant interactive systems to inform people that they are interacting with AI. They must also support machine-readable marking of synthetic or manipulated text, image, video and audio so its origin can be detected, subject to scope and exceptions. Deployers have disclosure duties when people encounter emotion-recognition or biometric-categorisation systems, deepfakes, or AI-generated public-interest text that has not received human review or editorial control.\n\nThese distinctions matter in schools. A student-facing support bot needs a clear AI notice. A synthetic voice or video used in public communication may need provenance and a perceivable label. A school that publishes an AI-drafted public-interest notice without meaningful human editorial control faces a different obligation from a teacher who uses AI to improve wording and then takes responsibility for the final text. Ordinary assistive editing that does not substantially alter the input or its meaning can fall outside some marking duties, depending on the detailed rules.\n\nThe Commission states that generative systems placed on the market before August 2 receive a transition for the machine-readable marking obligation until December 2026. It also describes maximum penalties of up to 15 million euros or 3% of worldwide annual turnover for companies, with proportionality provisions. Schools should obtain appropriate legal advice for their role and jurisdiction rather than treating a short product-news summary as a compliance determination.\n\nArticle 50 is not the entire AI Act and is not a complete checklist for high-risk uses in education. It does not by itself resolve whether a particular admissions, assessment, monitoring or emotion-analysis system is lawful, fair or educationally justified. Transparency also cannot make an inaccurate or discriminatory system acceptable. A visible label is one control within a larger process that includes purpose limitation, data protection, human oversight, accessibility and challenge routes.\n\nA useful school inventory can record every interactive AI surface and every channel that publishes generated media. For each one, the institution can identify provider and deployer roles, intended audience, human review, machine-readable provenance, visible disclosure, retention, responsible owner and evidence that the notice is understandable to children. Procurement contracts should preserve the information needed to meet those duties.\n\nFor Hong Kong organizations serving EU users or partnering with European institutions, role and territorial scope need case-specific review. More broadly, the rule offers a transferable design principle: learners, families and staff should know when AI is interacting, generating or transforming content, and should know who remains accountable for the decision or message.`,
    keyTakeaways: [
      "Product news policy brief: Article 50 transparency obligations began applying on August 2, 2026, with duties divided between providers and deployers.",
      "The rules address AI-interaction notices, machine-readable marking, deepfake and public-interest-text labels, emotion recognition and biometric categorisation.",
      "Transparency is one layer, not the whole education or high-risk-AI framework; schools still need data protection, human oversight, accessibility and challenge processes.",
    ],
    whyItMatters: "For AIEDHK, Article 50 turns AI disclosure into a systems inventory: institutions need to know where AI interacts or creates content, which role they hold and who remains accountable after the label appears.",
    sourceUrl: "https://digital-strategy.ec.europa.eu/en/news/commission-publishes-guidelines-transparency-obligations-providers-and-deployers-certain-ai-systems",
    sourceUrls: [
      { label: "European Commission: Article 50 transparency guidelines", url: "https://digital-strategy.ec.europa.eu/en/news/commission-publishes-guidelines-transparency-obligations-providers-and-deployers-certain-ai-systems" },
      { label: "European Commission: Quick facts on AI transparency rules", url: "https://digital-strategy.ec.europa.eu/en/factpages/quick-facts-transparency-rules-ai-systems" },
    ],
    createdAt: "2026-08-02",
  },
  {
    id: "aied-060",
    slug: "k12-chatgpt-adaptation-prompt-scaffolds",
    title: "A brief prompt scaffold changed how secondary students used ChatGPT but did not improve knowledge gain",
    authors: ["Maria Klar"],
    venue: "Smart Learning Environments",
    year: 2025,
    type: "journal",
    tags: ["K-12", "ChatGPT", "prompt scaffolding", "interaction patterns", "knowledge gain"],
    image: "/images/research/covers/aied-060-k12-chatgpt-adaptation-prompt-scaffolds-2026.png",
    imageAlt: "German secondary students refine AI questions with prompt cards while a researcher observes their inquiry process in a small learning lab",
    summaryImage: "/images/research/summary/aied-060-k12-chatgpt-adaptation-prompt-scaffolds-summary.png",
    summaryImageAlt: "German secondary students refine AI questions with prompt cards while a researcher observes their inquiry process in a small learning lab",
    summaryAudio: "/audio/research/aied-060-k12-chatgpt-adaptation-prompt-scaffolds-summary.m4a",
    summaryAudioTitle: "Listen to the paper summary",
    shortSummary: "In an experiment with 106 German Grade 9–10 students, a 2.5-minute instruction and interface suggestions more than doubled adaptation prompts during a 20-minute ChatGPT research task. The support changed interaction behaviour but did not significantly improve knowledge gain or cognitive load.",
    fullSummary: `Klar asks why students who find ChatGPT easy to operate may still use only a small part of its learning potential. The mixed-methods experiment involved 106 Grade 9 and 10 students from five German secondary schools. In small after-school sessions, groups were randomly assigned to use a ChatGPT-3.5 research interface with or without additional support. Both groups investigated cognitive biases for 20 minutes. The supported group received about 2.5 minutes of instruction, suggestions for follow-up and adaptation prompts, and controls for response length and language difficulty.\n\nThe support clearly changed interaction behaviour. Students in the supported condition used an average of 6.00 adaptation prompts, compared with 2.51 in the comparison condition. The difference was statistically significant with a large reported effect, partial eta-squared of .283. Supported students also asked more total questions, 7.8 compared with 4.8, used more follow-ups and engaged in less off-topic conversation. Chat logs therefore show that a small scaffold can make student dialogue more iterative and tailored.\n\nThe learning measures tell a different story. The support did not significantly reduce extraneous cognitive load and did not significantly improve knowledge gain. Both groups reported high usability and satisfaction. That combination is educationally important: liking a chatbot and asking more sophisticated questions do not guarantee that learners understand or retain more. Interaction quality may be a mechanism worth developing, but it remains an intermediate outcome unless linked to independent learning evidence.\n\nThe study is deliberately small and bounded. Students completed one unfamiliar topic in a 20-minute session and could not use ordinary web search alongside the chatbot. The sample may be too small to detect modest learning effects. Explicitly telling the supported group that adaptation is helpful could create demand characteristics. The research does not establish long-term self-regulated learning, transfer across subjects or how students use unrestricted tools at home.\n\nFor classroom design, the findings argue against treating a list of prompt tips as a complete intervention. Teachers can combine question adaptation with source comparison, retrieval and explanation. For example, a student might request a simpler explanation, then identify a claim to verify, compare it with an assigned source and explain the concept without the chat. A teacher can score both the inquiry process and the unaided explanation.\n\nThe interface also matters. Follow-up suggestions can help novices notice options they might not invent, but they can channel every learner into the same pattern or add cognitive clutter. Supports should be optional, age-appropriate and tested with learners who have different language proficiency and accessibility needs.\n\nFor Hong Kong schools, bilingual studies could test whether language controls support Cantonese- and English-medium learning without simplifying disciplinary meaning. Longer units should measure delayed retention and transfer. The paper's central lesson is precise: brief prompting support changed what students did with ChatGPT, but this experiment did not show that the behavioural change improved learning.`,
    keyTakeaways: [
      "A randomized small-group experiment involved 106 Grade 9–10 students completing a 20-minute ChatGPT research task.",
      "Brief support increased adaptation prompts from 2.51 to 6.00 and total questions from 4.8 to 7.8, with more follow-up interaction.",
      "Knowledge gain and extraneous cognitive load did not improve significantly, so interaction change should not be reported as a learning effect.",
    ],
    whyItMatters: "For AIEDHK, the study supplies a clean measurement distinction: prompt scaffolds can change observable AI-use behaviour, but schools still need independent assessments to show whether learning changes.",
    sourceUrl: "https://doi.org/10.1186/s40561-025-00385-2",
    sourceUrls: [
      { label: "Smart Learning Environments article", url: "https://doi.org/10.1186/s40561-025-00385-2" },
    ],
    createdAt: "2026-08-02",
  },
  {
    id: "aied-059",
    slug: "news-gemini-docs-multilingual-education-rollout",
    title: "Product news: Gemini in Docs begins a multilingual education rollout that includes Mandarin",
    authors: ["Google Workspace"],
    venue: "AI Product and Learning Report",
    year: 2026,
    type: "policy-ethics",
    tags: ["product news", "Gemini in Docs", "multilingual education", "Mandarin", "education licensing"],
    image: "/images/research/covers/aied-059-gemini-docs-multilingual-education-rollout-2026.png",
    imageAlt: "A multilingual teacher team refines a bilingual lesson document with source materials and formatting examples on a large classroom display",
    summaryImage: "/images/research/summary/aied-059-gemini-docs-multilingual-education-rollout-summary.png",
    summaryImageAlt: "A multilingual teacher team refines a bilingual lesson document with source materials and formatting examples on a large classroom display",
    summaryAudio: "/audio/research/aied-059-gemini-docs-multilingual-education-rollout-summary.m4a",
    summaryAudioTitle: "Listen to the product news report",
    shortSummary: "Product news: Google scheduled expanded Gemini in Docs language support to begin rolling out to Scheduled Release domains on August 1. Mandarin joined ten other languages for document creation, writing-style matching and format matching, with education access limited to eligible plans and settings.",
    fullSummary: `Google's August 1 rollout milestone expands several Gemini in Docs capabilities to 11 additional languages: Mandarin, Dutch, Malay, Hebrew, Polish, Turkish, Czech, Indonesian, Swedish, Danish and Norwegian. Rapid Release domains began earlier, while Scheduled Release domains were set to start gradual rollout on August 1, with up to 15 days for feature visibility. For multilingual education, Mandarin support is the most directly relevant change for many Hong Kong teachers, but rollout and licensing boundaries remain important.\n\nThe updated Docs experience includes Help me create and Help me write, along with tools for matching writing style and document format. Google describes a workflow that can synthesize context from Drive, Gmail, Chat and the web into a formatted first draft. In a school, that could help a teacher begin a bilingual lesson outline, adapt a family communication or bring a document into a familiar template. It should not be treated as authoritative translation, curriculum alignment or a substitute for subject editing.\n\nGoogle lists Education Plus and the Teaching and Learning or Google AI Pro for Education add-ons among the education access routes. Administrators must enable Gemini for Workspace in Drive, and users must enable Workspace smart features. The capability is not described as a universal feature of Education Fundamentals. A gradual rollout also means that two eligible teachers in the same period may not see the same interface.\n\nLanguage availability is different from language quality. Mandarin output may use vocabulary, register or examples that do not fit Hong Kong classrooms, and Chinese-English documents can hide inconsistencies in names, dates, assessment criteria or disciplinary terminology. Match writing style can reproduce an existing tone, including its biases or accessibility problems. Match document format can make a draft look institutionally approved before its content has been checked.\n\nA responsible workflow should preserve the source material and identify which passages were generated or transformed. Teachers can compare key claims line by line, check quotations and links, use a shared terminology list and ask a second reviewer to inspect high-stakes communications. Student information should enter only an approved workspace and only when necessary. Connected email, chat and Drive context increases usefulness, but it also increases the importance of permissions and data minimization.\n\nSchools can evaluate the feature with a small set of ordinary tasks: a bilingual parent notice, a lesson outline and an accessible handout. Measures can include total drafting and review time, factual and terminology errors, reading level, formatting repair and whether the final document serves its audience better than the original process. Teachers who use different languages and accessibility tools should participate.\n\nThe product-news value is not simply that another language appears in a menu. The rollout makes context-aware document generation more reachable for multilingual teams while exposing a new review problem: fluent formatting can create false confidence. Educational quality still depends on human authorship, local language judgment, protected context and evidence that the document communicates accurately.`,
    keyTakeaways: [
      "Product news: Scheduled Release rollout began August 1 for 11 additional Gemini in Docs languages, including Mandarin.",
      "Education access depends on eligible plans, administrator enablement, user smart-feature settings and a gradual rollout of up to 15 days.",
      "Schools should test terminology, bilingual consistency, connected-data permissions, accessibility and full review time rather than equating fluent formatting with quality.",
    ],
    whyItMatters: "For AIEDHK, Mandarin support can lower a practical language barrier, but the release also demonstrates why bilingual educational content needs source preservation, terminology control and human review.",
    sourceUrl: "https://workspaceupdates.googleblog.com/2026/07/expanded-language-support-for-gemini-in-Google-Docs.html",
    sourceUrls: [
      { label: "Google Workspace: Expanded language support for Gemini in Docs", url: "https://workspaceupdates.googleblog.com/2026/07/expanded-language-support-for-gemini-in-Google-Docs.html" },
    ],
    createdAt: "2026-08-01",
  },
  {
    id: "aied-058",
    slug: "tutor-copilot-human-ai-real-time-expertise",
    title: "Tutor CoPilot improved short-term topic mastery by supporting human tutors, with the largest gain among lower-rated tutors",
    authors: ["Rose E. Wang", "Ana T. Ribeiro", "Carly D. Robinson", "Susanna Loeb", "Dora Demszky"],
    venue: "arXiv preprint",
    year: 2025,
    type: "journal",
    tags: ["human-AI tutoring", "K-12 mathematics", "randomized trial", "tutor professional learning", "topic mastery"],
    image: "/images/research/covers/aied-058-tutor-copilot-human-ai-real-time-expertise-2026.png",
    imageAlt: "A human tutor guides a middle-school learner through mathematics while a discreet AI panel suggests questions rather than answers",
    summaryImage: "/images/research/summary/aied-058-tutor-copilot-human-ai-real-time-expertise-summary.png",
    summaryImageAlt: "A human tutor guides a middle-school learner through mathematics while a discreet AI panel suggests questions rather than answers",
    summaryAudio: "/audio/research/aied-058-tutor-copilot-human-ai-real-time-expertise-summary.m4a",
    summaryAudioTitle: "Listen to the paper summary",
    shortSummary: "A tutor-level randomized trial across 782 active tutors and 1,787 Grade 3–8 students found that Tutor CoPilot access raised short-term lesson mastery by four percentage points and by nine points for lower-rated tutors. It did not significantly improve the year-end mathematics test.",
    fullSummary: `Wang and colleagues test a human-AI design that supports tutors during instruction rather than placing a chatbot in front of students. Tutor CoPilot reads the current mathematics problem and tutor-student conversation, then suggests guidance such as a probing question, explanation, hint or similar problem. The human tutor decides whether to use or edit the suggestion. The preregistered tutor-level randomized trial was conducted with a virtual tutoring provider and nine Title I schools in one southern U.S. district.\n\nAt launch, 782 tutors were active, with 386 assigned access and 396 in control. They served 1,787 students in Grades 3 through 8 across 4,136 mathematics sessions over two months, producing more than 550,000 messages. The primary causal outcome was whether a student mastered the lesson topic on the provider's exit ticket. Access to Tutor CoPilot increased that mastery rate by four percentage points in the intention-to-treat analysis. For students taught by tutors who had lower prior quality ratings, the gain was nine percentage points.\n\nConversation analysis suggests a mechanism. Tutors with access used more guiding questions, asked learners to explain reasoning and gave fewer direct answers. The system may therefore distribute elements of expert tutoring practice at the moment they are needed. At the study's usage level, the authors estimate language-model cost at about 20 dollars per tutor per year. That figure excludes product development, training, monitoring, privacy, support and wider deployment costs.\n\nThe longer-term result is essential: the study did not find a statistically significant improvement on the end-of-year mathematics test. The exit ticket is a meaningful proximal measure, but it cannot establish durable achievement or transfer. The work also took place with one provider and district over two months, with variable tool use. Some suggestions were not grade-appropriate, and de-identifying names cannot prevent learners from revealing other personal details in free conversation.\n\nFor implementation, the human-in-the-loop architecture is promising only if the human remains capable and accountable. Tutors need training to reject a plausible but poor suggestion, adapt language to the learner and protect personal information. Providers can evaluate suggestion quality by topic, grade and tutor experience, sample interactions for human review and show tutors why a recommended move may help. A system that silently optimizes acceptance rates could undermine that judgment.\n\nFor Hong Kong tutoring and school support, a pilot should test local curricula, Cantonese and English dialogue and varied learner needs. Outcomes can include immediate mastery, delayed unaided problems, tutor practice and equity across tutor experience. Full cost should include onboarding and review.\n\nThe paper's strongest finding is appropriately narrow: real-time AI support improved short-term topic mastery and especially helped learners served by lower-rated tutors. Whether that support produces sustained learning remains unproven, making delayed independent assessment a necessary next step.`,
    keyTakeaways: [
      "The tutor-level trial included 782 active tutors, 1,787 Grade 3–8 students, 4,136 sessions and more than 550,000 messages.",
      "Tutor CoPilot increased proximal topic mastery by four percentage points overall and nine points for students of lower-rated tutors.",
      "The year-end mathematics test did not significantly improve, so the evidence supports short-term mastery and changed tutor practice, not durable achievement.",
    ],
    whyItMatters: "For AIEDHK, Tutor CoPilot demonstrates a strong human-AI pattern: use AI to strengthen a tutor's questions and explanations, then evaluate both near-term mastery and what students retain later without assistance.",
    sourceUrl: "https://arxiv.org/abs/2410.03017",
    sourceUrls: [
      { label: "arXiv: Tutor CoPilot", url: "https://arxiv.org/abs/2410.03017" },
    ],
    createdAt: "2026-08-01",
  },
  {
    id: "aied-057",
    slug: "news-microsoft-elevate-educator-expert-deadline",
    title: "Product news: Microsoft Elevate reaches its Educator Expert deadline with free AI-literacy credential pathways",
    authors: ["Microsoft"],
    venue: "AI Product and Learning Report",
    year: 2026,
    type: "policy-ethics",
    tags: ["product news", "Microsoft Elevate", "teacher credentials", "AI literacy", "professional learning"],
    image: "/images/research/covers/aied-057-microsoft-elevate-educator-expert-deadline-2026.png",
    imageAlt: "Korean and international educators complete an AI-literacy learning pathway and compare credential evidence in a professional development centre",
    summaryImage: "/images/research/summary/aied-057-microsoft-elevate-educator-expert-deadline-summary.png",
    summaryImageAlt: "Korean and international educators complete an AI-literacy learning pathway and compare credential evidence in a professional development centre",
    summaryAudio: "/audio/research/aied-057-microsoft-elevate-educator-expert-deadline-summary.m4a",
    summaryAudioTitle: "Listen to the product news report",
    shortSummary: "Product news: July 31 was the application deadline for Microsoft Elevate for Educators' 2026–27 Expert Track. The programme connects Explorer, Expert and school-recognition routes with free Microsoft–ISTE+ASCD credential learning pathways, while regional eligibility and the value of recognition still require careful review.",
    fullSummary: `July 31 was the closing date for applications to the 2026–27 Microsoft Elevate for Educators Expert Track. Microsoft announced the Korea launch of its broader educator initiative on June 25, so the date is a deadline rather than a new product launch. Results were scheduled for late September. The programme combines a global educator community, professional credentials, guided learning and recognition routes for both educators and schools.\n\nThe application sequence is operationally specific. Microsoft instructs educators to create both Microsoft Learn and Microsoft Elevate accounts and make the display names match exactly. They should complete Explorer Basic, which remains available year-round, then pursue either the General or AI Expert learning path before applying for Educator Expert recognition. Schools can begin with Pathfinder School and apply for Showcase School recognition through a separate route.\n\nMicrosoft describes professional credential learning pathways developed with ISTE+ASCD as free and aligned with the OECD AI Literacy Framework. The framework emphasizes engaging with, creating with, managing and designing AI. A Korean AI-literacy credential programme co-developed with Seoul National University's Center for Future Education Innovation was scheduled to open its K-12 educator pathway in September. The official page does not establish that every global or Hong Kong educator qualified for the July application, and it does not separately price every recognition process.\n\nThe distinction between learning and recognition matters. A free course can widen access to professional development, while a badge or expert title can motivate sustained participation and peer exchange. Neither proves that a teacher can evaluate AI output, protect student data or improve learning. Recognition systems may also favour educators who already have time, devices, English proficiency, institutional support or access to Microsoft tools.\n\nSchools can evaluate a credential pathway by inspecting its tasks and evidence. Does it require teachers to test factual accuracy, document data decisions, design an age-appropriate learning activity and reflect on a failure? Are classroom artifacts reviewed, or is completion based mainly on watching content and answering short checks? Can educators use the learning across vendors, subjects and languages? These questions matter more than the prestige of a badge.\n\nFor Hong Kong professional learning, the reusable pattern is a staged route from entry-level learning to demonstrated practice and community contribution. A local programme could pair a free foundation with bilingual workshops, peer review, classroom inquiry and recognition that counts toward school development. It should provide protected time and alternative access so recognition does not deepen inequity.\n\nThe deadline is therefore useful product and programme news, not evidence of educational impact. Microsoft Elevate offers a visible pathway and a free credential-learning offer, but teachers and institutions still need to verify eligibility, examine assessment quality and decide whether the resulting practice benefits learners.`,
    keyTakeaways: [
      "Product news: July 31 was the Expert Track application deadline; Microsoft had announced the programme earlier, so it should not be described as a same-day launch.",
      "Applicants need matching Microsoft Learn and Elevate identities, Explorer Basic and a General or AI Expert pathway before Expert recognition.",
      "Microsoft describes the credential learning pathways as free, but schools should verify regional eligibility and evaluate demonstrated practice rather than badge completion alone.",
    ],
    whyItMatters: "For AIEDHK, Microsoft Elevate provides a concrete teacher-development ladder while highlighting the evidence question every credential must answer: what can an educator demonstrably do after completion?",
    sourceUrl: "https://news.microsoft.com/source/asia/features/microsoft-elevate-for-educators-korea-2026-en/",
    sourceUrls: [
      { label: "Microsoft: Elevate for Educators launches in Korea", url: "https://news.microsoft.com/source/asia/features/microsoft-elevate-for-educators-korea-2026-en/" },
    ],
    createdAt: "2026-07-31",
  },
  {
    id: "aied-056",
    slug: "generative-ai-guardrails-high-school-mathematics",
    title: "Unguarded GPT raised assisted practice scores but reduced unaided mathematics performance in a high-school RCT",
    authors: ["Hamsa Bastani", "Osbert Bastani", "Alp Sungu", "Haosen Ge", "Özge Kabakcı", "Rei Mariman"],
    venue: "Proceedings of the National Academy of Sciences",
    year: 2025,
    type: "journal",
    tags: ["generative AI", "high school mathematics", "randomized controlled trial", "pedagogical guardrails", "independent learning"],
    image: "/images/research/covers/aied-056-generative-ai-guardrails-high-school-mathematics-2026.png",
    imageAlt: "Turkish high-school students solve mathematics problems in three classroom conditions while teachers compare assisted practice with a later unaided test",
    summaryImage: "/images/research/summary/aied-056-generative-ai-guardrails-high-school-mathematics-summary.png",
    summaryImageAlt: "Turkish high-school students solve mathematics problems in three classroom conditions while teachers compare assisted practice with a later unaided test",
    summaryAudio: "/audio/research/aied-056-generative-ai-guardrails-high-school-mathematics-summary.m4a",
    summaryAudioTitle: "Listen to the paper summary",
    shortSummary: "In a preregistered cluster RCT with nearly 1,000 Turkish high-school students, a standard GPT-4 interface raised assisted practice performance by 48% but reduced later unaided exam performance by 17%. A teacher-informed tutor raised practice performance by 127% and largely removed the penalty without creating a positive exam gain.",
    fullSummary: `Bastani and colleagues test whether the design of a generative-AI tutor changes what students learn, not only what they complete while assisted. Their preregistered cluster randomized controlled trial took place in one large Turkish high school during the 2023–24 school year. About 50 Grade 9, 10 and 11 classes, comprising nearly 1,000 students, completed four 90-minute mathematics sessions. Classes were assigned to ordinary textbooks and notes, a ChatGPT-like GPT-4 interface called GPT Base, or a guarded GPT Tutor.\n\nEach session separated assisted practice from independent performance. Students first solved practice problems with their assigned resources, then completed a related exam without any resource. GPT Base used a general tutor prompt and could provide answers. GPT Tutor was instructed to give hints rather than direct solutions and received teacher-authored correct solutions, common errors and feedback guidance for each problem. That problem-specific information made the tutor more reliable but required substantial teacher preparation.\n\nBoth AI conditions improved visible practice performance. Relative to control, GPT Base raised practice scores by 48% and GPT Tutor by 127%. The unaided exam reversed the picture for the unguarded system: GPT Base students scored 17% below control. GPT Tutor students were statistically indistinguishable from control, meaning the guardrails largely removed the penalty but did not produce a significant positive exam gain.\n\nSystem accuracy and student behaviour help explain the difference. When repeatedly asked for answers to the study's 57 practice problems, GPT Base was correct only 51% of the time, with 42% logical errors and 8% arithmetic errors. Yet the researchers find that errors alone do not explain the exam penalty. Chat logs show that GPT Base students often requested and copied solutions, while GPT Tutor students increasingly attempted answers and asked for help. Students also did not appear to recognise how superficial use could affect later performance.\n\nThe study should not be generalized into a claim that all generative AI harms learning. It covers one school, one subject, four sessions and a GPT-4-era configuration. The material represented about 15% of the semester curriculum. The guarded tutor was unusually well supplied with teacher-created problem knowledge and remained reactive rather than diagnosing misconceptions like an expert human tutor. Longer-term retention and transfer were not established.\n\nFor classroom design, the decisive outcome is what students can do after assistance is removed. A school can restrict direct answers, require a learner attempt before a hint, ground feedback in verified solutions and include a short unaided transfer problem. Logs can be used for aggregate design improvement rather than punitive surveillance.\n\nFor Hong Kong mathematics education, replication should test local curricula, bilingual interaction and varied achievement levels. The result gives a precise warning and a design direction: a fluent tool can raise immediate scores while weakening engagement, and pedagogical guardrails can mitigate harm only when teachers define the knowledge, hints and independent evidence that matter.`,
    keyTakeaways: [
      "Nearly 1,000 students in about 50 classes completed a preregistered cluster RCT with control, GPT Base and teacher-informed GPT Tutor conditions.",
      "GPT Base raised practice performance by 48% but lowered unaided exams by 17%; GPT Tutor raised practice by 127% and largely removed the penalty without a positive exam gain.",
      "The evidence is specific to one mathematics setting and a labour-intensive guarded design, supporting independent assessment rather than a universal anti-AI conclusion.",
    ],
    whyItMatters: "For AIEDHK, this RCT makes the central design test concrete: educational AI should be judged by independent learning after the tool is removed, not by the polish or score of AI-assisted practice alone.",
    sourceUrl: "https://doi.org/10.1073/pnas.2422633122",
    sourceUrls: [
      { label: "PNAS article", url: "https://doi.org/10.1073/pnas.2422633122" },
    ],
    createdAt: "2026-07-31",
  },
] satisfies ResearchPaper[]).map((paper) => ({
  ...paper,
  fullSummary: `${paper.fullSummary}\n\n${editorialClosers[paper.id]}`,
}));
